### ISSUE TITLE
NullPointerException during startup/deployment

### ISSUE THREAD

**Issue by bencomp** [europeana/REPOX#11]
When I start the Tomcat server (in Docker using Fig), I see a `NullPointerException` and an error of which I don't know if it's related:

```
repox_1 | 25-Feb-2015 15:39:49.302 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /usr/local/tomcat/webapps/repox.war
repox_1 | DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:113) - OAIHandler.init(..): No 'org.oclc.oai.server.OAIHandler.properties' servlet context attribute. Trying to use init parameter 'properties'
repox_1 | DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:118) - fileName=oaicat.properties
repox_1 | DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:121) - file not found. Try the classpath: oaicat.properties
repox_1 | DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:125) - file was found: Load the properties
repox_1 | WARN pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:63) - Using DEFAULT configuration properties file: configuration.properties
repox_1 | INFO pt.utl.ist.configuration.DefaultRepoxManager.<init>(DefaultRepoxManager.java:116) - DefaultRepoxManager creating.
repox_1 | java.lang.NullPointerException
repox_1 | 	at java.io.Reader.<init>(Reader.java:78)
repox_1 | 	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
repox_1 | 	at pt.utl.ist.util.FileUtilSecond.createFile(FileUtilSecond.java:308)
repox_1 | 	at pt.utl.ist.configuration.DefaultRepoxManager.<init>(DefaultRepoxManager.java:126)
repox_1 | 	at pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:64)
repox_1 | 	at pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:25)
repox_1 | 	at org.oclc.oai.util.OAIUtil.getTag(OAIUtil.java:233)
repox_1 | 	at org.oclc.oai.server.catalog.XMLRecordFactory.<init>(XMLRecordFactory.java:25)
repox_1 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
repox_1 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
repox_1 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
repox_1 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
repox_1 | 	at org.oclc.oai.server.catalog.AbstractCatalog.factory(AbstractCatalog.java:384)
repox_1 | 	at org.oclc.oai.server.OAIHandler.getAttributes(OAIHandler.java:187)
repox_1 | 	at org.oclc.oai.server.OAIHandler.init(OAIHandler.java:128)
repox_1 | 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
repox_1 | 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
repox_1 | 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
repox_1 | 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901)
repox_1 | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188)
repox_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
repox_1 | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
repox_1 | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
repox_1 | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
repox_1 | 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:917)
repox_1 | 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1701)
repox_1 | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
repox_1 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
repox_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
repox_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
repox_1 | 	at java.lang.Thread.run(Thread.java:745)
repox_1 | ERROR pt.utl.ist.metadataTransformation.MetadataTransformationManager.loadMetadataTransformations(MetadataTransformationManager.java:449) - Error loading the metadata transformations file (metadataTransformations.xml).
```

I compiled using the `-Pproduction` flag and did not change the oaicat.properties file. In the configuration.properties file I only changed the address of the database server.

Is the error related to the exception? Why can't it find the metadataTransformations.xml file? (Is it deprecated?)

**Comment by stzanakis** [comment]
No it's not deprecated.
I think you pulled a version on the middle of some updates I was doing.
What is the latest commit of your local repo? The latest in github is `d051fb7f5ad31cf18079b9dd005c0c066b6b82e6`.
Can you verify that, and pull the latest version?

**Comment by stzanakis** [comment]
Aah and btw, just noticed you said docker and fig, Repox is not compatible to run on a Paas service, at least not yet. So you might be able to install it, but everytime you redeploy you will lose your information.

**Comment by bencomp** [comment]
Oh, so you pushed unfinished business ;)

I can run and stop the containers for MySQL and REPOX and start them again where I left. It should be possible to share a local directory with the containers to store harvested (and configuration(?)) data outside a container, so that a new image can pick up on the old data. Is there information that is not in the DB or /data/repoxData/ directory? Mmm, the configuration.properties I guess - but if that information doesn't change, I should be fine, right?

**Comment by stzanakis** [comment]
Kinda, is it ok now?

I am not familiar with Docker,but yes if you can maintain the directory data then you should be fine. And yes if the information in the `configuration.properties` doesn't change you should be fine.
But you can also use  the JVM system variable to use another configuration directory, check [Configuration files](https://github.com/europeana/REPOX/wiki/Using-configuration-files) . Then you can copy the configuration files in there and customise them, then if the files get updated while repox is deployed the changes will be persisted.

**Comment by bencomp** [comment]
The updated code doesn't throw the NullPointerException anymore. Thanks!
