### ISSUE TITLE
Unable to load DefaultRepoxManager

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#17]
Hi, 
I'm running into the following error with a build of the latest version of REPOX. The build completes with 0 errors, but when I deploy the repox.war to Tomcat I have problems.

Any suggestions for what to check? 

Thank you!

```
INFO: Deploying web application archive /usr/home/bridger/src/apache-tomcat-7.0.53/webapps/repox.war
DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:113) - OAIHandler.init(..): No 'org.oclc.oai.server.OAIHandler.
properties' servlet context attribute. Trying to use init parameter 'properties'
DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:118) - fileName=oaicat.properties
DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:121) - file not found. Try the classpath: oaicat.properties
DEBUG org.oclc.oai.server.OAIHandler.init(OAIHandler.java:125) - file was found: Load the properties
FATAL pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:53) - Unable to load 
DefaultRepoxManager
java.lang.NullPointerException
        at pt.utl.ist.configuration.DefaultRepoxConfiguration.<init>(DefaultRepoxConfiguration.java:27)
        at pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:44)
        at pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:21)
        at org.oclc.oai.util.OAIUtil.getTag(OAIUtil.java:233)
        at org.oclc.oai.server.catalog.XMLRecordFactory.<init>(XMLRecordFactory.java:25)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.oclc.oai.server.catalog.AbstractCatalog.factory(AbstractCatalog.java:384)
        at org.oclc.oai.server.OAIHandler.getAttributes(OAIHandler.java:187)
        at org.oclc.oai.server.OAIHandler.init(OAIHandler.java:128)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5210)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5493)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.NullPointerException
        at org.oclc.oai.util.OAIUtil.getTag(OAIUtil.java:233)
        at org.oclc.oai.server.catalog.XMLRecordFactory.<init>(XMLRecordFactory.java:25)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.oclc.oai.server.catalog.AbstractCatalog.factory(AbstractCatalog.java:384)
        at org.oclc.oai.server.OAIHandler.getAttributes(OAIHandler.java:187)
        at org.oclc.oai.server.OAIHandler.init(OAIHandler.java:128)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5210)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5493)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
FATAL pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:53) - Unable to load 
DefaultRepoxManager
```

**Comment by stzanakis** [comment]
Hi there,

First of all I would suggest to get a copy of the development branch, cause master has still some bugs.
And from the stack trace I think you have the "default.email.pass" property empty or removed from the "configuration.properties" file.
Is that so?

**Comment by CanOfBees** [comment]
I did have default.email.pass and default.email commented out on my latest test. I uncommented those lines, switched to the development branch, rebuilt and it looks like things are working now.

As always, thank you for your help!
