### ISSUE TITLE
Missing configuration/* files

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#2]
Hello there. After building and trying to run the repox-gui-2.6.0-SNAPSHOT.war in Tomcat, I'm getting the following errors:
```
FATAL - Unable to load DefaultRepoxManager
java.io.FileNotFoundException: /vhosts/repoxdata/configuration/countries.txt (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:52)
...//snip//...

Load Config files from Java Variables -- No Pre-Configured Log4j File found for REPOX
java.io.FileNotFoundException: /vhosts/repoxdata/configuration/metadataSchemas.xml (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at pt.utl.ist.util.XmlUtil.writePrettyPrint(XmlUtil.java:37)
...//snip//...
```
I was able to fix the first error by copying the `countries.txt` from `manager/target/classes/` up to our test server, but I'm not seeing a `metadataSchemas.xml`. Is this a file that should be included or generated in the repository, or should we be rolling our own?

Thanks for your time and trouble.
Cheers.

**Comment by stzanakis** [comment]
Hello!
Your permission in the directories is not correct.
I'm guessing that the /vhosts directory has root permissions and it doesn't allow tomcat to write in it.
Please make sure with which user you run tomcat, root or not and the permissions on the /vhosts folder, it has to be writable from others.
And yes, metadataSchemas.xml is generated from Repox.

Cheers.

**Comment by CanOfBees** [comment]
That fixed that problem. Thanks!
