### ISSUE TITLE
Add United States to countries

### ISSUE THREAD

**Issue by CTDA** [europeana/REPOX#27]
I noticed while playing with this version that to set up a data provider there is no option for the US. Could this be added?

**Comment by stzanakis** [comment]
Sorry for the late reply.
Did you try the option "Use Countries File?" from the Administration->Configuration settings?

**Comment by CTDA** [comment]
We tried your suggestion but ended up with a JAVA error.
Checking the option expanded the list of country options

[9:46]  
However, when editing the test CTDA harvest and changing the country to USA caused a JAVA Null pointer error along with a corresponding JAVA fault message...

[9:46]  
INFO: Server startup in 48353 ms
java.net.MalformedURLException: no protocol:
       at java.net.URL.<init>(URL.java:585)
       at java.net.URL.<init>(URL.java:482)
       at java.net.URL.<init>(URL.java:431)
       at harvesterUI.server.projects.DefaultSaveData.saveDataProvider(DefaultSaveData.java:587)
       at harvesterUI.server.projects.DefaultProjectManager.saveDataProvider(DefaultProjectManager.java:671)
       at harvesterUI.server.dataManagement.dataProviders.DPServiceImpl.saveDataProvider(DPServiceImpl.java:20)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)
       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
       at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)

....

**Comment by stzanakis** [comment]
What version of Repox do you have installed?
When you create the provider try to provide a valid url on the homepage field.
Does that work?

**Comment by CTDA** [comment]
We're on the 3.1.0 that we got from this repo.

**Comment by stzanakis** [comment]
Ok I have fixed it on the development branch.
Added US at the default list as well, that is without using the countries file.

If you want to have the updated countries.txt file you need to copy and replace the file for example.
`cp ~/REPOX/manager/src/main/resources/countries.txt /data/repoxData/configuration/`

**Comment by CTDA** [comment]
Thanks much.
