### ISSUE TITLE
EmailSender error when adding a new user

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#3]
I'm getting the following error when I save a new user account [1]. Are we missing a component on the server or could this be a configuration error? This is on CentOS 7.0.1.

Thanks!

[1] from catalina.out
```
java.io.IOException: Unable to send email
        at pt.utl.ist.util.EmailSender.sendEmail(EmailSender.java:166)
        at pt.utl.ist.rest.util.DefaultEmailUtil.sendEmail(DefaultEmailUtil.java:68)
        at harvesterUI.server.projects.DefaultProjectManager.sendUserDataEmail(DefaultProjectManager.java:809)
        at harvesterUI.server.userManagement.UserManagementServiceImpl.sendUserDataEmail(UserManagementServiceImpl.java:610)
        at harvesterUI.server.userManagement.UserManagementServiceImpl.saveUser(UserManagementServiceImpl.java:305)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at harvesterUI.server.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1024)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
        at org.springframework.mail.MailSendException.toString(MailSendException.java:124)
        at java.lang.String.valueOf(String.java:2847)
        at java.lang.StringBuilder.append(StringBuilder.java:128)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:695)
        at java.lang.Throwable.printStackTrace(Throwable.java:667)
        at java.lang.Throwable.printStackTrace(Throwable.java:643)
        at java.lang.Throwable.printStackTrace(Throwable.java:634)
        at harvesterUI.server.projects.DefaultProjectManager.sendUserDataEmail(DefaultProjectManager.java:816)
        at harvesterUI.server.userManagement.UserManagementServiceImpl.sendUserDataEmail(UserManagementServiceImpl.java:610)
        at harvesterUI.server.userManagement.UserManagementServiceImpl.saveUser(UserManagementServiceImpl.java:305)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at harvesterUI.server.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1024)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by stzanakis** [comment]
Hello again! :)

You need to fix your configuration when you login as admin. Administration->Configuration Settings
Specifically the fields:

REPOX Default Email Sender : "Your email account that will be used as a sender email"
Administrator Email Password : "The email's password"

Without quotes of course.

What happens is that when you submit the form you will get an email to your account with the generated password.

Cheers!

**Comment by CanOfBees** [comment]
:) thank you for your patient help. I've tried modifying the REPOX Default Email Sender and Administrator Email Password but continue to have problems. 

I've tried using a Gmail acct, with SSL enabled in REPOX and 'Access for less secure apps' turned on, but get an error [1]. I've also tried to use settings that are similar to the settings in our instance running in Jetty [2] - this fails with the original error.

I'm probably missing something obvious. 
Cheers

[1]
   Administrator Email: a_gmail_acct@gmail.com
   SMTP Server: smtp.gmail.com
   SMTP Port: 465
   REPOX Default Email Sender: a_gmail_acct@gmail.com
   Administrator Email Password: SOUPERSEKRET!!1! 

```
 java.lang.NullPointerException
        at harvesterUI.server.userManagement.UserManagementServiceImpl.sendUserDataEmail(UserManagementServiceImpl.java:610)
        at harvesterUI.server.userManagement.UserManagementServiceImpl.saveUser(UserManagementServiceImpl.java:305)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at harvesterUI.server.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1024)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
[2] 
   Administrator Email: a_utk_acct@utk.edu
   SMTP Server: smtp.utk.edu
   SMTP Port: 25
   REPOX Default Email Sender: repo@our.server.name.edu
   Administrator Email Password: abc123

**Comment by stzanakis** [comment]
In my instance I used the gmail configuration as yours, with my credentials and it works.
Do you have the latest version of REPOX?
I am out of ideas of what can be happening and I cannot debug your instance, so please try to rebuild repox and test again.

Thanks!

**Comment by CanOfBees** [comment]
I've tried rebuilding, with a variety of options set in REPOX/resources/src/main/resources/configuration.properties but I'm still getting errors. We are going to try to make sure it isn't an issue with the OS.

Thanks!

**Comment by stzanakis** [comment]
Hi there,

Wanted to let you know that the, administrator email is used only for receiving information that repox sends. The REPOX Default Email Sender is for sending information and the Administrator Email Password is actually for the REPOX Default Email Sender. Probably that's why you were having issues.
I updated some backend info so it must be more clear now, if you update and clear history when deployed.

Cheers.
