### ISSUE TITLE
Error(s) using xsl:include in a stylesheet

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#34]
Hi Simon -

I'm getting the following error when I try to use `xsl:include` in a transform. The `included` file has been added via the MDR but is *not* explicitly applied to the dataset in question. I've added the stack trace below. The [stylesheet itself](https://gist.github.com/CanOfBees/0c7a6fc2c4367f3577f32ae453840153) is a simple identity transform and the `xsl:include`d file is the [FunctX stylesheet](https://gist.github.com/CanOfBees/3f554f0e5ffdc4bad644912485a9bbcf). Any thoughts or suggestions for working around this?

From a poor reading of the error, I would think that this has something to do with how Repox is caching the stylesheets in the configuration directory (`/data/repoxData/configuration/xslt` in my case), and I'm curious if there's some other way to set this up.

As a precaution, I commented the `xsl:include` and reassociated the transform and the stylesheet worked as expected. So, despite checking everything I can think of (associations in repox, adding the included stylesheet via the MDR UI, checking ownership/permissions on the file system), I'm at a loss. 

Thank you for your help.
Best,
Bridger

-- Error --
``` text
2017-05-14T16:18:04.212Z ERROR pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog:619 [http-nio-8080-exec-6] - Error Transforming record, may be an error in xslt -  Set: $
est01 ID: ba5701a4-436f-4ed3-b998-d0e5f8e8ccc7
javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 96 errors detected.
        at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:140)
        at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:135)
        at pt.utl.ist.metadataTransformation.Xslt2StylesheetCache.getTransformationTemplate(Xslt2StylesheetCache.java:54)
        at pt.utl.ist.metadataTransformation.Xslt2StylesheetCache.createTransformer(Xslt2StylesheetCache.java:41)
        at pt.utl.ist.metadataTransformation.MetadataTransformationManager.loadStylesheet(MetadataTransformationManager.java:104)
        at pt.utl.ist.metadataTransformation.MetadataTransformation.transform(MetadataTransformation.java:224)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.getTransformedRecord(DataSourceOaiCatalog.java:922)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.getRecordsFromDataSet(DataSourceOaiCatalog.java:587)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.getListRecords(DataSourceOaiCatalog.java:478)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.listRecords(DataSourceOaiCatalog.java:255)
        at org.oclc.oai.server.verb.ListRecords.construct(ListRecords.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.oclc.oai.server.OAIHandler.getResult(OAIHandler.java:441)
        at org.oclc.oai.server.OAIHandler.doGet(OAIHandler.java:335)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:155)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at harvesterUI.server.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1504)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1460)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by CanOfBees** [comment]
Hi Simon - 
regards, but it looks like my problem is due to a Saxon version incompatibility issue. Sorry for the noise.

Best,
Bridger
