### ISSUE TITLE
Error when attempting to transform data

### ISSUE THREAD

**Issue by fruviad** [europeana/REPOX#42]
I've installed REPOX (latest development version) on a CentOS 7 server.

I'm using data sources and XSLT files that I know are working on another REPOX server (running an older release of REPOX).

When I attempt to pull untransformed data from REPOX on the new server, it works without problems.  However, if I try to pull transformed data, REPOX throws the following error in the /var/log/tomcat/repox.log:

```
javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
        at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:140)
        at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:135)
        at pt.utl.ist.metadataTransformation.Xslt2StylesheetCache.getTransformationTemplate(Xslt2StylesheetCache.java:54)
        at pt.utl.ist.metadataTransformation.Xslt2StylesheetCache.createTransformer(Xslt2StylesheetCache.java:41)
        at pt.utl.ist.metadataTransformation.MetadataTransformationManager.loadStylesheet(MetadataTransformationManager.java:104)
        at pt.utl.ist.metadataTransformation.MetadataTransformation.transform(MetadataTransformation.java:232)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.getTransformedRecord(DataSourceOaiCatalog.java:1000)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.getRecordsFromDataSet(DataSourceOaiCatalog.java:621)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.getListRecords(DataSourceOaiCatalog.java:478)
        at pt.utl.ist.oai.server.catalog.DataSourceOaiCatalog.listRecords(DataSourceOaiCatalog.java:255)
        at org.oclc.oai.server.verb.ListRecords.construct(ListRecords.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.oclc.oai.server.OAIHandler.getResult(OAIHandler.java:441)
        at org.oclc.oai.server.OAIHandler.doGet(OAIHandler.java:335)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:155)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at harvesterUI.server.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

The browser displays the following error:

```
HTTP Status 500 - Failed to compile stylesheet. 1 error detected.
type Status report
message Failed to compile stylesheet. 1 error detected.
description The server encountered an internal error that prevented it from fulfilling this request.
Apache Tomcat/7.0.76

```

I added a few "log.error()" entries to the code and was able to determine that the exact line of code where the failure is happening is line 224 of the "manager/src/main/java/pt/utl/ist/metadataTransformation/MetadataTransformation.java" file.  That chunk of code reads as follows:

```
    222     public String transform(String identifier, String xmlSourceString, String dataProviderName) throws DocumentException, TransformerException, NullPointerException {
    223         try {
    224             Transformer transformer = ConfigSingleton.getRepoxContextUtil().getRepoxManager().getMetadataTransformationManager().loadStylesheet(this);
    225
    226             Document sourceDocument = DocumentHelper.parseText(xmlSourceString);
    227             DocumentSource source = new DocumentSource(sourceDocument);
    228             DocumentResult result = new DocumentResult();
    229
    230             transformer.clearParameters();
    231             transformer.setParameter("recordIdentifier", identifier);
    232             transformer.setParameter("dataProvider", dataProviderName);
    233
    234             // Transform the source XML to System.out.
    235             transformer.transform(source, result);
    236             Document transformedDoc = result.getDocument();
    237
    238             return transformedDoc.asXML();
    239         } catch (NullPointerException e) {
    240             throw new NullPointerException();
    241         }
    242     }
```

EDIT:  Further digging (Java isn't my first language...bear with me!) shows that the code is also getting at least to line 103 of manager/src/main/java/pt/utl/ist/metadataTransformation/MetadataTransformationManager.java via the call in line 224 of MetadataTransformation.java before the error occurs:

```
    101     public Transformer loadStylesheet(MetadataTransformation metadataTransformation) throws TransformerException {
    102         File xsltFile = new File(xsltDir, metadataTransformation.getStylesheet());
    103         if (metadataTransformation.isVersionTwo()) {
    104             return xslt2StylesheetCache.createTransformer(xsltFile);
    105         } else {
    106             TransformerFactory tfactory = new org.apache.xalan.processor.TransformerFactoryImpl();
    107             Source xsltSource = new StreamSource(xsltFile);
    108             return tfactory.newTransformer(xsltSource);
    109         }
    110     }
```

I've tested some of the XSLT files using the command line and an appropriate XML file on the new server, and I'm sure that the XSLT isn't bad.

I've enabled DEBUG logging, but that's not giving me any more information about the actual cause of the problem.

At this point I'm not sure of what else I can look at to get more details about what might be going wrong.  Do you have any thoughts on what might be wrong, or how I can find more evidence to help diagnose the problem?

[root@server]# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

[root@server]# yum info tomcat
Name        : tomcat
Arch        : noarch
Version     : 7.0.76
Release     : 9.el7_6
Size        : 303 k
Repo        : installed
From repo   : updates
Summary     : Apache Servlet/JSP Engine, RI for Servlet 3.0/JSP 2.2 API

**Comment by stzanakis** [comment]
Hi there,

Ok so you managed the configuration here I suppose, so the other issue https://github.com/europeana/REPOX/issues/41 is not relevant anymore? If so please close it.

Generally I have to say that at the moment we are not having budget to support REPOX since we are working on other things. So I will try to guess what's going on here.

From the investigation you did I think, maybe, the call to metadataTransformation.isVersionTwo() is transferring the execution to the wrong block and then. So let's say the xslt version is actually true but the call metadataTransformation.isVersionTwo() returns false, which then goes to the wrong block and returns the wrong transformer which in turn fails to compile the stylesheet if it's the wrong version.

One thing you could try is under the configuration there is a file `configuration/metadataTransformations.xml` where you could potentially update to the correct version for each xslt and restart repox. Maybe that could help.

Otherwise I would try to check with both versions of xslt or modify the code to only use the block that is required for the xslt version you are using. If that works the next point is to find out where the metadataTransformation object is created and why the versionTwo field is not set properly.

In the worst case, probably you need to re-import the xslts from the ui.

The above are just some guesses, so I don't know if this could be of any help for you, but please let me know.
