### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by neshelman** [europeana/REPOX#5]
I'm trying to install repox. I downloaded the project from https://github.com/europeana/REPOX today and ran  mvn clean install -Pproduction. I'm on RHEL 6. I get these errors: What do I need to do to get it to install? Thanks. --Nicholas

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 150 source files to /opt/installed/REPOX-master/commons/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] REPOX-SYSTEM ....................................... SUCCESS [ 12.724 s]
[INFO] REPOX-COMMONS ...................................... FAILURE [ 51.253 s]
[INFO] REPOX-MANAGER ...................................... SKIPPED
[INFO] REPOX-RESOURCES .................................... SKIPPED
[INFO] REPOX-SERVER ....................................... SKIPPED
[INFO] REPOX-SERVER-OAI ................................... SKIPPED
[INFO] REPOX-SERVER-REST-JERSEY ........................... SKIPPED
[INFO] REPOX-GUI .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2015-01-20T13:23:45-05:00
[INFO] Final Memory: 13M/33M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project repox-commons: Fatal error compiling: invalid target release: 1.7 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :repox-commons
[root@ip-10-45-143-236 REPOX-master]#
[root@ip-10-45-143-236 REPOX-master]#
[root@ip-10-45-143-236 REPOX-master]# pwd
/opt/installed/REPOX-master
[root@ip-10-45-143-236 REPOX-master]# ls

**Comment by stzanakis** [comment]
The java version you are using is incorrect. Please fix your JAVA_HOME to a 1.7 jdk

**Comment by stzanakis** [comment]
Before rebuilding please pull  the latest version cause I made an update regarding builds

**Comment by neshelman** [comment]
Simon, Thanks very much. I was able to get it to build (I also didn't have enough RAM on my puny EC2 VM).  I'll get the latest version. --Nicholas

**Comment by neshelman** [comment]
Hi Simon, I built the latest repox, but it won't deploy in tomcat 6. I get the following in catalina.out. Thanks --Nicholas
 
Jan 21, 2015 1:29:29 PM org.apache.catalina.startup.HostConfig deployWAR
SEVERE: Error deploying web application archive repox-server-oai-2.6.0-SNAPSHOT.war
java.lang.UnsupportedClassVersionError: org/oclc/oai/server/OAIHandler : Unsupported major.minor version 51.0 (unable to load class org.oclc.oai.server.OAIHandler)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2334)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:976)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1450)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1329)
        at org.apache.catalina.startup.WebAnnotationSet.loadApplicationServletAnnotations(WebAnnotationSet.java:108)
        at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:58)
        at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:294)
        at org.apache.catalina.startup.ContextConfig.start(ContextConfig.java:1046)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:265)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4616)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:526)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:905)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:525)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1359)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:297)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:856)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:805)
        at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1475)
        at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:250)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:558)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:701)

**Comment by stzanakis** [comment]
I tested again, the newest build on my local tomcat 6 and it is working.

Are you deploying the repox-server-oai-2.6.0-SNAPSHOT.war or the repox-gui-2.6.0-SNAPSHOT.war ??

Another guess, is that you build it using java version 7 and now you are running it on the server where your tomcat6 is located with a java version 6. Is that the case?

**Comment by neshelman** [comment]
Hi Simon, Yes, it was that tomcat was using a jre not the jdk. Thanks! Can you please tell me a bit about the status and history of repox? I've been asked to get it working for the University of Connecticut (I'm a sys admin). 
I see that on the "original site" there is user documentation 
http://repox.sysresearch.org/ for an old version
Manual - REPOX v2.0.16
Is that documentation valid for your version or is there documentation for your version somewhere else? --Nicholas

**Comment by stzanakis** [comment]
I'm glad it works now! 
For other questions, non related to this issue, please open another issue with a label question, or just drop me an email.

Thank you!

**Comment by neshelman** [comment]
Hi Simon, First of all, I really appreciate your willingness to answer my questions.  Can you please tell me if the documentation here is http://repox.sysresearch.org<http://repox.sysresearch.org/> valid for the version you are developing? Thanks –Nicholas

**Comment by stzanakis** [comment]
The user documentation at http://repox.sysresearch.org is the only one existent but I am not maintaining it. It is still valid though for most of the stuff(some parts removed or named differently), but you can work with it.
